# 数据的清洗和准备

## 处理缺失数据

In [2]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark', 'artichoke',np.nan,'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### 滤除缺失数据

In [6]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data = pd.DataFrame([[1., 6.5, 3.], [1. , NA, NA],
                    [NA,NA,NA],[NA,6.5 ,3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [10]:
cleaned#dtopna丢弃任何含有缺失值的行

0    1    2
0  1.0  6.5  3.0

In [11]:
data.dropna(how='all')#how='all'只丢弃全为NA的那些行，若要丢弃列，只需传入'axis=1'即可

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [12]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [13]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [14]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.294913       NaN       NaN
1  0.624266       NaN       NaN
2 -0.163183       NaN -0.174232
3 -0.712021       NaN -1.255627
4 -0.826023  0.806762  1.579532
5 -0.882242  0.746652 -0.933207
6 -1.861052  1.174225  1.435133

In [15]:
df.dropna()

0         1         2
4 -0.826023  0.806762  1.579532
5 -0.882242  0.746652 -0.933207
6 -1.861052  1.174225  1.435133

In [16]:
df.dropna(thresh=2)#thresh可以留下你只想留下的一部分观测数据

0         1         2
2 -0.163183       NaN -0.174232
3 -0.712021       NaN -1.255627
4 -0.826023  0.806762  1.579532
5 -0.882242  0.746652 -0.933207
6 -1.861052  1.174225  1.435133

### 填充缺失数据

In [17]:
df.fillna(0)

0         1         2
0 -0.294913  0.000000  0.000000
1  0.624266  0.000000  0.000000
2 -0.163183  0.000000 -0.174232
3 -0.712021  0.000000 -1.255627
4 -0.826023  0.806762  1.579532
5 -0.882242  0.746652 -0.933207
6 -1.861052  1.174225  1.435133

In [18]:
df.fillna({1: 0.5,2: 0})

0         1         2
0 -0.294913  0.500000  0.000000
1  0.624266  0.500000  0.000000
2 -0.163183  0.500000 -0.174232
3 -0.712021  0.500000 -1.255627
4 -0.826023  0.806762  1.579532
5 -0.882242  0.746652 -0.933207
6 -1.861052  1.174225  1.435133

In [19]:
_ = df.fillna(0, inplace=True)
df

0         1         2
0 -0.294913  0.000000  0.000000
1  0.624266  0.000000  0.000000
2 -0.163183  0.000000 -0.174232
3 -0.712021  0.000000 -1.255627
4 -0.826023  0.806762  1.579532
5 -0.882242  0.746652 -0.933207
6 -1.861052  1.174225  1.435133

In [21]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] =NA
df

0         1         2
0  0.642389 -3.489933 -0.252510
1 -0.290751  0.190108 -1.995945
2 -0.838366       NaN -0.655849
3 -0.179072       NaN -0.465666
4  0.420681       NaN       NaN
5 -2.119625       NaN       NaN

In [22]:
df.fillna(method='ffill')

0         1         2
0  0.642389 -3.489933 -0.252510
1 -0.290751  0.190108 -1.995945
2 -0.838366  0.190108 -0.655849
3 -0.179072  0.190108 -0.465666
4  0.420681  0.190108 -0.465666
5 -2.119625  0.190108 -0.465666

In [23]:
df.fillna(method='ffill' , limit=2)#limit()对于向前和向后填充可以连续填充最大数量

0         1         2
0  0.642389 -3.489933 -0.252510
1 -0.290751  0.190108 -1.995945
2 -0.838366  0.190108 -0.655849
3 -0.179072  0.190108 -0.465666
4  0.420681       NaN -0.465666
5 -2.119625       NaN -0.465666

In [24]:
data = pd.Series([1. , NA , 3.5 , NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## 数据转换

### 移除重复数据

In [26]:
data = pd.DataFrame({'k1' : ['one' , 'two'] * 3 + ['two'],'k2' : [1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [27]:
data.duplicated()#duplicated()判断各行是否是重复值

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [31]:
data.drop_duplicates()#返回一个DataFrame

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [33]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [34]:
data.drop_duplicates(['k1' , 'k2'], keep='last')# keep='last'保留最后一个

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### 利用函数或映射进行数据转换

In [46]:
data = pd.DataFrame({'food' : ['bacon' , 'pulled pork','bacon',
                              'Pastrami', 'corned beef','Bacon',
                              'pastrami' , 'honey ham' , 'nova lox'],
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [47]:
meat_to_animal = {
    'bacon' : 'pig',
    'pulled pork' : 'cow',
    'pastrami' : 'cow',
    'corned beef' : 'cow',
    'honey ham' : 'pig',
    'nova lox' : 'salmon'
}

In [48]:
lowercased = data['food'].str.lower()#把各个值转化为小写
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [49]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     cow
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [50]:
data['food'].map(lambda x: meat_to_animal[x.lower()])#map()是一种实现元素级转换以及其他数据清理工作的便捷方式

0       pig
1       cow
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

### 替换值

In [51]:
data = pd.Series([1., -999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [52]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [53]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [54]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [55]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### 重命名轴索引

In [59]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio','Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
transform = lambda x: x[:4].upper()
data.index.map(transform)       

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [60]:
data.index = data.index.map(transform)

In [61]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [62]:
data.rename(index={'OHIO': 'INDIANA'},
           columns={'three': 'peekaboo'})#rename()创建数据集的转换版

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [63]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [64]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

### 离散化和面元划分

In [65]:
ages = [20,22,25,27,21,23,37,31,61,45,41,31]
bins = [18,25,35,60,100]
cats = pd.cut(ages, bins)
cats#cut()划分数据

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [66]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [67]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [68]:
pd.value_counts(cats)#是pandas.cut结果的面元计数

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [69]:
pd.cut(ages,[18,26,36,61,100], right=False)#哪边是闭端可以通过right/left=false修改

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [70]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [73]:
data = np.random.randn(20)
pd.cut(data, 4, precision=2)

[(-0.18, 0.72], (-1.08, -0.18], (-0.18, 0.72], (0.72, 1.62], (-1.08, -0.18], ..., (-0.18, 0.72], (-0.18, 0.72], (0.72, 1.62], (-1.98, -1.08], (-1.08, -0.18]]
Length: 20
Categories (4, interval[float64]): [(-1.98, -1.08] < (-1.08, -0.18] < (-0.18, 0.72] < (0.72, 1.62]]

In [74]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats

[(-3.483, -0.632], (0.733, 2.956], (-3.483, -0.632], (0.733, 2.956], (-0.632, 0.0664], ..., (0.733, 2.956], (0.733, 2.956], (0.733, 2.956], (0.733, 2.956], (-0.632, 0.0664]]
Length: 1000
Categories (4, interval[float64]): [(-3.483, -0.632] < (-0.632, 0.0664] < (0.0664, 0.733] < (0.733, 2.956]]

In [75]:
pd.value_counts(cats)

(0.733, 2.956]      250
(0.0664, 0.733]     250
(-0.632, 0.0664]    250
(-3.483, -0.632]    250
dtype: int64

In [76]:
pd.qcut(data, [0,0.1,0.5,0.9,1.])

[(-3.483, -1.243], (0.0664, 1.351], (-1.243, 0.0664], (0.0664, 1.351], (-1.243, 0.0664], ..., (1.351, 2.956], (0.0664, 1.351], (0.0664, 1.351], (0.0664, 1.351], (-1.243, 0.0664]]
Length: 1000
Categories (4, interval[float64]): [(-3.483, -1.243] < (-1.243, 0.0664] < (0.0664, 1.351] < (1.351, 2.956]]

### 检测和过滤异常值

In [77]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.046529     0.014520    -0.047285    -0.032386
std       1.005703     0.970537     0.966815     1.001542
min      -3.211037    -3.571443    -2.681491    -3.320252
25%      -0.598661    -0.637906    -0.726461    -0.712210
50%       0.088812     0.052063    -0.077023    -0.030642
75%       0.663888     0.680132     0.621444     0.651922
max       3.386116     2.977901     3.443056     2.775051

In [78]:
col = data[2]
col[np.abs(col) > 3]

232    3.443056
Name: 2, dtype: float64

In [79]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
32   3.386116  0.077791 -0.220017 -0.406266
66  -3.211037 -0.874195  0.819146  0.593316
232  0.484574 -1.315783  3.443056  1.006857
274  3.133633 -0.891726 -1.307151  0.181829
285  3.094225 -1.867026 -0.947770 -0.567501
326 -0.048994 -0.770365  1.500521 -3.162042
367 -0.262035 -3.397141 -1.736835  2.200493
486 -2.072431 -3.571443 -1.400630  0.778940
644 -1.340169 -3.034175  0.489088 -0.219575
688 -2.073208  0.154403  0.383798 -3.207258
695 -3.168813  0.715961  1.263367  1.059611
766  1.018076 -0.124831  0.716499 -3.320252
784 -0.025732 -3.376014 -0.868029 -1.347137

In [80]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.046295     0.015899    -0.047728    -0.031696
std       1.002618     0.965915     0.965314     0.999408
min      -3.000000    -3.000000    -2.681491    -3.000000
25%      -0.598661    -0.637906    -0.726461    -0.712210
50%       0.088812     0.052063    -0.077023    -0.030642
75%       0.663888     0.680132     0.621444     0.651922
max       3.000000     2.977901     3.000000     2.775051

In [81]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0 -1.0 -1.0
1 -1.0 -1.0 -1.0  1.0
2 -1.0 -1.0 -1.0  1.0
3  1.0 -1.0 -1.0 -1.0
4  1.0  1.0 -1.0 -1.0

### 排列和随机采样

In [82]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5,4)))
sampler = np.random.permutation(5)#np.random.permutation可以轻松实现对Series和DataFrame的排列工作
sampler

array([1, 2, 4, 0, 3])

In [83]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [84]:
df.take(sampler)

0   1   2   3
1   4   5   6   7
2   8   9  10  11
4  16  17  18  19
0   0   1   2   3
3  12  13  14  15

In [85]:
df.sample(n=3)

0   1   2   3
0   0   1   2   3
2   8   9  10  11
3  12  13  14  15

In [86]:
choices = pd.Series([5, 7, -1, 6, 4])
draws = choices.sample(n=10, replace = True)
draws

3    6
0    5
1    7
3    6
0    5
4    4
1    7
4    4
2   -1
1    7
dtype: int64

### 计算指标/哑变量

In [87]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                  'datal': range(6)})
pd.get_dummies(df['key'])#get_dummies可以派生出一个K（一列中含有不同值的个数）列矩阵或DF

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [88]:
dummies = pd.get_dummies(df['key'],prefix='key')
df_with_dummy = df[['datal']].join(dummies)
df_with_dummy

datal  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [89]:
mnames = ['movie_id','title','genres']
movies = pd.read_table('datasets/movielens/movies.dat',
                      sep="::",
                      header=None, names=mnames)
movies[:10]

D:\python\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: read_table is deprecated, use read_csv instead.
  after removing the cwd from sys.path.
D:\python\lib\site-packages\ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [90]:
all_genres = []
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)

In [91]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [93]:
zero_matrix = np.zeros((len(movies),len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [95]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [96]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [98]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [99]:
bins = [0,0.2, 0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

## 字符串操作

### 字符串对象方法

In [100]:
val = 'a,b, guido'
val.split(",")

['a', 'b', ' guido']

In [101]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [102]:
first,second ,third = pieces
first + '::' + 'second' + '::' +'third'

'a::second::third'

In [103]:
'::'.join(pieces)

'a::b::guido'

In [104]:
'guido' in val

True

In [105]:
val.index(',')

1

In [106]:
val.find(':')

-1

In [107]:
val.index(':')#若找不到字符串，index会发生异常

ValueError: substring not found

In [108]:
val.count(',')

2

In [109]:
val.replace(',','::')

'a::b:: guido'

In [111]:
val.replace(',','')

'ab guido'

### 正则表达式

In [112]:
import re

In [113]:
text = "foo   bar\t  baz   \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [114]:
#对于大量字符串，以下操作可以节约CPU的时间
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [115]:
regex.findall(text)

['   ', '\t  ', '   \t']

### pandas的矢量化字符串函数

In [117]:
data = {'Dave':'dave@goole.com','Steve':'steve@gmail.com',
       'Rob':'rob@gmail.com','Wes':np.nan}
data = pd.Series(data)
data

Dave      dave@goole.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [118]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [119]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [120]:
pattern

NameError: name 'pattern' is not defined

In [121]:
data.str.findall(pattern,flags=re.IGNORECASE)

NameError: name 'pattern' is not defined